default:
  golem_name: metabarMap
  golem_version: 0.0.0.9000
  app_prod: no
  station_ids: ["ST1","ST10","ST11","ST12","ST13","ST2","ST3","ST4","ST5","ST6","ST7","ST8","ST9"]
production:
  app_prod: yes
dev:
  golem_wd: !expr golem::pkg_path()
